/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BukuKos.ui;

/**
 *
 * @author HP
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_datakamar = new javax.swing.JButton();
        btn_datapenghuni = new javax.swing.JButton();
        btn_datatagihan = new javax.swing.JButton();
        btn_pengguna = new javax.swing.JButton();
        btn_exit2 = new javax.swing.JButton();
        btn_exit = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/logo bukukos kcl bgt.png"))); // NOI18N
        jLabel1.setText("BUKUKOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("SELAMAT DATANG ADMIN !");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/bedroom.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 170, 90, 71));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/women.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 61, 65));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/invoice.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 60, 57));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/user.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 60, 50));

        jTextField1.setBackground(new java.awt.Color(102, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        btn_datakamar.setBackground(new java.awt.Color(153, 0, 0));
        btn_datakamar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_datakamar.setForeground(new java.awt.Color(255, 255, 255));
        btn_datakamar.setText("DATA KAMAR");
        btn_datakamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datakamarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_datakamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, -1));

        btn_datapenghuni.setBackground(new java.awt.Color(153, 0, 0));
        btn_datapenghuni.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_datapenghuni.setForeground(new java.awt.Color(255, 255, 255));
        btn_datapenghuni.setText("DATA PENGHUNI");
        btn_datapenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datapenghuniActionPerformed(evt);
            }
        });
        getContentPane().add(btn_datapenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));

        btn_datatagihan.setBackground(new java.awt.Color(153, 0, 0));
        btn_datatagihan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_datatagihan.setForeground(new java.awt.Color(255, 255, 255));
        btn_datatagihan.setText("DATA TAGIHAN");
        btn_datatagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datatagihanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_datatagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 110, -1));

        btn_pengguna.setBackground(new java.awt.Color(153, 0, 0));
        btn_pengguna.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_pengguna.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengguna.setText("REGISTER");
        btn_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 23));

        btn_exit2.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/logout.png"))); // NOI18N
        btn_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 40, 40));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/11.png"))); // NOI18N
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_datatagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datatagihanActionPerformed
        new DataTagihan().show();
        this.dispose();
    }//GEN-LAST:event_btn_datatagihanActionPerformed

    private void btn_exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit2ActionPerformed
        new MasukAkun().show();
        this.dispose();
    }//GEN-LAST:event_btn_exit2ActionPerformed

    private void btn_datakamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datakamarActionPerformed
        new DataKamar().show();
        this.dispose();
    }//GEN-LAST:event_btn_datakamarActionPerformed

    private void btn_datapenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datapenghuniActionPerformed
        new DataPenghuni().show();
        this.dispose();
    }//GEN-LAST:event_btn_datapenghuniActionPerformed

    private void btn_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penggunaActionPerformed
        new DataAkun().show();
        this.dispose();
    }//GEN-LAST:event_btn_penggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datakamar;
    private javax.swing.JButton btn_datapenghuni;
    private javax.swing.JButton btn_datatagihan;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JButton btn_exit2;
    private javax.swing.JButton btn_pengguna;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
