/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BukuKos.ui;

import BukuKos.helper.Koneksi2;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import BukuKos.model.DataKamar2;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class DataKamar extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form DataKamar
     */
    public DataKamar() {
        initComponents();
        fetchData();
    }

    //penempatan dan pencocokan data tabel di database dan di tabel JTable
    private void fetchData() {
        ArrayList<DataKamar2> list = dataKamar();
        DefaultTableModel model = (DefaultTableModel) kamar_table.getModel();
        Object[] row = new Object[5];

        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId_kamar();
            row[1] = list.get(i).getLantai();
            row[2] = list.get(i).getFasilitas();
            row[3] = list.get(i).getTarif();
            model.addRow(row);
        }
    }

    //perintah untuk memasukkan data ke dalam tabel dan select data
    public ArrayList<DataKamar2> dataKamar() {
        ArrayList<DataKamar2> dataKamar = new ArrayList<>();
        try {
            Connection con = Koneksi2.getConnection();
            String sql = "SELECT id_kamar, lantai, fasilitas, tarif FROM tb_kamar";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DataKamar2 DataKamar;
            while (rs.next()) {
                DataKamar = new DataKamar2(rs.getString("id_kamar"), rs.getInt("lantai"), rs.getString("fasilitas"), rs.getInt("tarif"));
                dataKamar.add(DataKamar);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return dataKamar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kamar_table = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idkamar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_lantai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tarif = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_fasilitas = new javax.swing.JTextArea();
        btn_tambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_cari02 = new javax.swing.JLabel();
        txt_cari4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kamar_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Kamar", "Lantai", "Fasilitas", "Tarif"
            }
        ));
        kamar_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kamar_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kamar_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 180));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, 30));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, 30));

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/refresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, 30));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/previous.png"))); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        jPanel1.setBackground(new java.awt.Color(220, 221, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("DATA KAMAR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/bedroom2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -20, 80, 70));

        txt_idkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idkamarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idkamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 520, -1));

        jLabel4.setText("ID Kamar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setText("Lantai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel1.add(txt_lantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, -1));

        jLabel3.setText("Fasilitas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setText("Tarif");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        jPanel1.add(txt_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 330, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txt_fasilitas.setColumns(20);
        txt_fasilitas.setRows(5);
        jScrollPane2.setViewportView(txt_fasilitas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 520, 60));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/button (1).png"))); // NOI18N
        btn_tambah.setText("  Data Kamar");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/11.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 670, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 250));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/logo bukukos kcl bgt.png"))); // NOI18N
        jLabel1.setText("BUKUKOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 116, 26));

        jTextField1.setBackground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari02.setForeground(new java.awt.Color(255, 255, 255));
        txt_cari02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BukuKos/icon/loupe.png"))); // NOI18N
        txt_cari02.setText("Cari Data");
        jPanel2.add(txt_cari02, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 90, 30));

        txt_cari4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari4ActionPerformed(evt);
            }
        });
        txt_cari4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari4KeyReleased(evt);
            }
        });
        jPanel2.add(txt_cari4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 670, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        new DashboardAdmin().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // masukan data ke dalam database
        try {
            Connection con = Koneksi2.getConnection();
            //query insert data ke dalam database mysql
            pst = con.prepareStatement("INSERT INTO tb_kamar (id_kamar, lantai, fasilitas, tarif) VALUES(?,?,?,?)");
            //validasi ketika textField kosong

            if (txt_idkamar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Kamar tidak boleh kosong");
            } else if (txt_lantai.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lantai tidak boleh kosong");
            } else if (txt_fasilitas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fasilitas tidak boleh kosong");
            } else if (txt_tarif.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tarif tidak boleh kosong");
            } else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, txt_idkamar.getText());
                pst.setString(2, txt_lantai.getText());
                pst.setString(3, txt_fasilitas.getText());
                pst.setString(4, txt_tarif.getText());
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                txt_idkamar.setText("");
                txt_lantai.setText("");
                txt_fasilitas.setText("");
                txt_tarif.setText("");

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        //untuk me refresh tabel
        DefaultTableModel model = (DefaultTableModel) kamar_table.getModel();
        model.setRowCount(0);
        fetchData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        //action button untuk mengedit data
        try {

            Connection con = Koneksi2.getConnection();
            int row = kamar_table.getSelectedRow();
            String value = (kamar_table.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE tb_kamar SET id_kamar=?,lantai=?,fasilitas=?,tarif=? WHERE id_kamar= '" + value + "'";
            if (txt_idkamar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Kamar tidak boleh kosong");
            } else if (txt_lantai.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lantai tidak boleh kosong");
            } else if (txt_fasilitas.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fasilitas tidak boleh kosong");
            } else if (txt_tarif.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tarif tidak boleh kosong");
            } else {
                pst = con.prepareStatement(sql);
                pst.setString(1, txt_idkamar.getText());
                pst.setString(2, txt_lantai.getText());
                pst.setString(3, txt_fasilitas.getText());
                pst.setString(4, txt_tarif.getText());
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) kamar_table.getModel();
                model.setRowCount(0);
                fetchData();
                txt_idkamar.setText("");
                txt_lantai.setText("");
                txt_fasilitas.setText("");
                txt_tarif.setText("");
                JOptionPane.showMessageDialog(null, "Edit Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void kamar_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kamar_tableMouseClicked
        //code ini berfungsi ngambil value di dalem tabel habisi itu dimasukin lagi ke textfield biar bisa di edit
        int i = kamar_table.getSelectedRow();
        TableModel model = kamar_table.getModel();
        txt_idkamar.setText(model.getValueAt(i, 0).toString());
        txt_lantai.setText(model.getValueAt(i, 1).toString());
        txt_fasilitas.setText(model.getValueAt(i, 2).toString());
        txt_tarif.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_kamar_tableMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {

            int row = kamar_table.getSelectedRow();
            Connection con = Koneksi2.getConnection();
            String value = (kamar_table.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM tb_kamar WHERE id_kamar = '" + value + "'";
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) kamar_table.getModel();
            model.setRowCount(0);
            fetchData();
            JOptionPane.showMessageDialog(null, "Data terhapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_idkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idkamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idkamarActionPerformed

    private void txt_cari4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari4ActionPerformed

    private void txt_cari4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari4KeyReleased
        DefaultTableModel table = (DefaultTableModel) kamar_table.getModel();
        String search = txt_cari4.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        kamar_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txt_cari4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable kamar_table;
    private javax.swing.JLabel txt_cari02;
    private javax.swing.JTextField txt_cari4;
    private javax.swing.JTextArea txt_fasilitas;
    private javax.swing.JTextField txt_idkamar;
    private javax.swing.JTextField txt_lantai;
    private javax.swing.JTextField txt_tarif;
    // End of variables declaration//GEN-END:variables
}
